spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/smartECommerce
    username: ${DB_USERNAME} #root
    password: ${DB_PASSWORD} #root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} #nihadmoosakoya@gmail.com
    password: ${MAIL_PASSWORD}   # pdzh qbvk oqys berh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true     
server:
  port: 8083

jwt:
  secret:  ${JWT_SECRET} #your_super_secret_key123456789987654321

